[package]
name = "mylib"
version = "0.1.0"
authors = ["maomao <you@example.com>"]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
reqwest = {version = "0.10.0", features = ["blocking"] }
base64 = "0.11.0"
